DataFrame objects

In [ ]:
#Creating a DataFrame
import pandas as pd

people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
}
people = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [ ]:
#Access columns of DataFrame
people['birthyear']

alice      1985
bob        1984
charles    1992
Name: birthyear, dtype: int64

In [ ]:
#Access multiple columns of DataFrame
people[['birthyear', 'hobby']]

         birthyear    hobby
alice         1985   Biking
bob           1984  Dancing
charles       1992      NaN

In [ ]:
d2 = pd.DataFrame(
        people_dict,
        columns=["birthyear", "weight", "height"],
        index=["bob", "alice", "eugene"]
     )
d2

        birthyear  weight height
bob        1984.0    83.0    NaN
alice      1985.0    68.0    NaN
eugene        NaN     NaN    NaN

In [ ]:
#Another convenient way to create a DataFrame
import numpy as np
values = [
            [1985, np.nan, "Biking",   68],
            [1984, 3,      "Dancing",  83],
            [1992, 0,      np.nan,    112]
         ]
d3 = pd.DataFrame(
        values,
        columns=["birthyear", "children", "hobby", "weight"],
        index=["alice", "bob", "charles"]
     )
d3

         birthyear  children    hobby  weight
alice         1985       NaN   Biking      68
bob           1984       3.0  Dancing      83
charles       1992       0.0      NaN     112

In [ ]:
#Instead of an ndarray, you can also pass a DataFrame object:
d4 = pd.DataFrame(
         d3,
         columns=["hobby", "children"],
         index=["alice", "bob"]
     )
d4

         hobby  children
alice   Biking       NaN
bob    Dancing       3.0

In [ ]:

#It is also possible to create a DataFrame with a dictionary (or list)
#of dictionaries (or lists):
people = pd.DataFrame({
    "birthyear": {"alice": 1985, "bob": 1984, "charles": 1992},
    "hobby": {"alice": "Biking", "bob": "Dancing"},
    "weight": {"alice": 68, "bob": 83, "charles": 112},
    "children": {"bob": 3, "charles": 0}
})
people

         birthyear    hobby  weight  children
alice         1985   Biking      68       NaN
bob           1984  Dancing      83       3.0
charles       1992      NaN     112       0.0

In [ ]:
#Multi-indexing
import pandas as pd
import numpy as np
d5 = pd.DataFrame(
  {
    ("public1", "birthyear"):
        {("Paris","alice"): 1985, ("Paris","bob"): 1984, ("London","charles"): 1992},
    ("public2", "hobby"):
        {("Paris","alice"): "Biking", ("Paris","bob"): "Dancing"},
    ("private1", "weight"):
        {("Paris","alice"): 68, ("Paris","bob"): 83, ("London","charles"): 112},
    ("private2", "children"):
        {("Paris", "alice"): np.nan, ("Paris","bob"): 3, ("London","charles"): 0}
  }
)
d5

                 public1  public2 private1 private2
               birthyear    hobby   weight children
Paris  alice        1985   Biking       68      NaN
       bob          1984  Dancing       83      3.0
London charles      1992      NaN      112      0.0

In [ ]:
#Access public columns:
d5['public1']

                birthyear
Paris  alice         1985
       bob           1984
London charles       1992

In [ ]:
#Access public1 and hobby columns:
d5['public1', 'hobby']

KeyError: 36

In [ ]:
#Dropping a level
d5

                 public1  public2 private1 private2
               birthyear    hobby   weight children
Paris  alice        1985   Biking       68      NaN
       bob          1984  Dancing       83      3.0
London charles      1992      NaN      112      0.0

In [ ]:
#Drop level
d5.columns = d5.columns.droplevel(level = 0)
d5

                birthyear    hobby  weight  children
Paris  alice         1985   Biking      68       NaN
       bob           1984  Dancing      83       3.0
London charles       1992      NaN     112       0.0

In [ ]:
#Transpsong
d6 = d5.T
d6

            Paris           London
            alice      bob charles
birthyear    1985     1984    1992
hobby      Biking  Dancing     NaN
weight         68       83     112
children      NaN      3.0     0.0

In [ ]:
#Stacking and unstacking levels
d7 = d6.stack()
d7

                  London    Paris
birthyear alice      NaN     1985
          bob        NaN     1984
          charles   1992      NaN
hobby     alice      NaN   Biking
          bob        NaN  Dancing
weight    alice      NaN       68
          bob        NaN       83
          charles    112      NaN
children  bob        NaN      3.0
          charles    0.0      NaN

In [ ]:
d8 = d7.unstack()
d8

          London                Paris
           alice  bob charles   alice      bob charles
birthyear    NaN  NaN    1992    1985     1984     NaN
children     NaN  NaN     0.0     NaN      3.0     NaN
hobby        NaN  NaN     NaN  Biking  Dancing     NaN
weight       NaN  NaN     112      68       83     NaN

In [ ]:
#Accessing rows
people

NameError: name 'people' is not defined